version: '3.8'

services:
  counter:
    build:
      context: ./Counter
      dockerfile: Dockerfile
    ports:
      - '3001:80'
    networks:
      - frontend-network

  navbar:
    build:
      context: ./navbar
      dockerfile: Dockerfile
    ports:
      - '3002:80'
    networks:
      - frontend-network

  host:
    build:
      context: ./host
      dockerfile: Dockerfile
    ports:
      - '3003:80'
    networks:
      - frontend-network
networks:
  frontend-network:
    driver: bridge
